typography_spectrum: 0.07269903784617782
color:
  brandStrength: 0.6563277128152549
  lightness: 0.5830820712726563
  saturation: 0.9118840843439102
  rhythmicContrast: 0.3656952022574842
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
layout_spectrum: 0.014030477963387966
name: RockinGlass.  custom barware to set your event apart from the heard
title: Glass makes it taste better.
description: Artist made in the USA.  Designed and Fabricated in Oakland California
